version: "3.8"
services:

  mongodb:
    image: mongo
    hostname: mongodb
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=artclash
    volumes:
      - ./data:/data/db

  app:
    build: .
    container_name: artclash-app
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    links:
      - mongodb
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/artclash

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
     - ME_CONFIG_MONGODB_SERVER=mongodb

volumes:
  data: {}

