version: "3.8"
services:
  artclash-service:
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres-container
    environment:
      - spring_datasource_url=${DATASOURCE_URL}
      - spring_datasource_username=${DATASOURCE_USERNAME}
      - spring_datasource_password=${DATASOURCE_PASSWORD}
  postgres-container:
    image: postgres:alpine
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./database/data:/data/db