version: "3.8"
services:
  artclash-service:
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres-container
  postgres-container:
    image: postgres:alpine
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: secretpassword
    volumes:
      - ./database/data:/data/db