version: "3.8"
services:
  artclash-service:
    build: .
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - spring_datasource_url=${DATASOURCE_URL}
      - spring_datasource_username=${DATASOURCE_USERNAME}
      - spring_datasource_password=${DATASOURCE_PASSWORD}
      - spring_datasource_driver-class-name=${DRIVER_CLASS}
      - spring_servlet_multipart_enabled=true
      - spring_servlet_multipart_max-file-size=5MB
      - spring_servlet_multipart_max-request-size=100MB
      - spring_jpa_properties_hibernate_dialect=org.hibernate.dialect.PostgreSQLDialect
      - spring_jpa_hibernate_ddl-auto=create-drop
      - spring_jpa_hibernate_show-sql=true
      - spring_config_import=${CONFIG_IMPORT_PATH}
  pg-admin:
    image: dpage/pgadmin4:6.20
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"

#  postgres-container:
#    image: postgres:alpine
#    restart: unless-stopped
#    expose:
#      - 5432
#    ports:
#      - "5432:5432"
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#      POSTGRES_DB: artclash
#    volumes:
#      - ./database/data:/var/lib/postgresql/data