version: "3.8"
services:
  artclash-service:
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mongo-container
  mongo-container:
    image: mongo:6.0.4
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb/data:/data/db